### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by bodrovis** [fossas/mocha-tape-deck#5]
Good day. We utilize this solution to test our API library at Lokalise. As far as I can tell, this library is not being maintained for quite some time already, and there are things to update/improve (the main problem is that it does not work with the latest Mocha). So, there are two possible options:

* Me and @kutanov may become maintainers of this repo and develop it further
* We'll create a separate solution based on this one while preserving the copyrights (mentioning the original authors etc). Perhaps, this option would be even better?..

**Comment by microsoftly** [comment]
We've not made additions to the repo since it has suited our needs.

We'd be happy to add you on as maintainers

**Comment by microsoftly** [comment]
We've not made additions to the repo since it has suited our needs.

Please submit PRs to add updates to the repo
